#!/bin/bash

CYCLE_START="271"
CYCLE_END="271"

cd ../data/downloaded_cygnss

for ((i = $CYCLE_START ; i <= $CYCLE_END ; i++)); do
    echo "Counter: $i"
    wget --http-user=wjb239 \
    --http-password=5NGvYoziBgij2TMp9f5 \
    -r \
    -nc \
    -np \
    -nd \
    -A "*.nc" \
    https://podaac-tools.jpl.nasa.gov/drive/files/allData/cygnss/L2/v3.0/2019/"$i"
done
