#!/bin/bash

CYCLE_START=$1
CYCLE_END=$2

cd ../data/downloaded_jason

for ((i = $CYCLE_START ; i <= $CYCLE_END ; i++)); do
    echo "Cycle: $i"
    wget --accept nc \
	 --mirror \
	 --page-requisites \
	 --adjust-extension \
	 --convert-links \
	 --backup-converted \
	 --no-parent \
	 --no-directories \
	 https://www.ncei.noaa.gov/data/oceans/jason3/gdr/gdr_ssha/cycle"$i"/
done
