#!/bin/bash

# download the cygnss data
#Rscript ../R_scripts/download_cygnss.R 2019 271 365
#Rscript ../R_scripts/download_cygnss.R 2020 1 269

# download the jason data
#./download_jason 133 170

# process both downloaded datasets
Rscript ../R_scripts/process_cygnss.R
Rscript ../R_scripts/process_jason.R

# put jason into daily files
Rscript ../R_scripts/create_daily_jason.R

# do the analyses
while IFS= read -r line
do
    Rscript ../R_scripts/fit_models.R $line

done < "../start_end_dates_small.txt"

# generate model plots
Rscript ../R_scripts/create_model_plots.R

# get data for empirical plots
while IFS= read -r line
do
    starboard_arg="${line} starboard"
    Rscript ../R_scripts/get_empirical_plot_data.R $starboard_arg
    port_arg="${line} port"
    Rscript ../R_scripts/get_empirical_plot_data.R $port_arg

done < "../start_end_dates_small.txt"

# generate empirical plots
Rscript ../R_scripts/create_empirical_plots.R